### PR TITLE
Add support for MultiPolygon

### PR DESCRIPTION
**Pull request by mmahrous**
1. Update JSZIP to v3.6.0 to support stream. 
2. Clean Geojson to take the geometries directly. 
3. Add support for multipolygon

### CODE REVIEW

**Comment by StruninIhor** [comment]
Good day everyone, @mapbox-re-oa, any updates on this?

**Comment by rangasatishkumar** [comment]
Eagerly waiting, when are these updates will be available?

**Comment by mmahrous** [comment]
@rangasatishkumar you can use it from our github directly
```
npm install https://github.com/transportforcairo/shp-write.git
```

until @mapbox-re-oa team merges it.

**Review by eneto774 — APPROVED** [review]

**Comment by Yohlo** [comment]
@mapbox-re-oa any updates on merging this?

**Comment by ngunner** [comment]
> @rangasatishkumar you can use it from our github directly
> 
> ```
> npm install https://github.com/transportforcairo/shp-write.git
> ```
> 
> until @mapbox-re-oa team merges it.

Thank you for this. However, JSZip V3 was giving me issues so I created a fork with only multipolygon fixes - https://github.com/ngunner/shp-write-multipolygon

If anyone has similar issues:
`npm install https://github.com/ngunner/shp-write-multipolygon.git`

**Comment by charlieforward9** [comment]
Could the `dbf` dependency also be upgrades to `0.2.0`. I am having this issue: https://github.com/mapbox/dbf/issues/23

**Pull request closed without merging**
